bancodedados = [{'email': 'vendedor',
                 'senha': '321',
                 'nome': 'teste',
                 'produtos': [{'codigo': 1, 'nome': 'camisa', 'valor': 10, 'quantidade': 3, 'descrição': 'Branca'},
                              {'codigo': 2, 'nome': 'chapeu', 'valor': 15, 'quantidade': 5, 'descrição': 'Vermelho'},
                              {'codigo': 3, 'nome': 'sapato', 'valor': 25, 'quantidade': 2, 'descrição': ''},
                              {'codigo': 4, 'nome': 'sandália', 'valor': 5, 'quantidade': 1, 'descrição': 'Fruta'}],
                 'saldo': 0,
                 'historico': []},

                {'email': 'cliente',
                 'senha': '123',
                 'nome': 'teste',
                 'produtos': [{'codigo': 5, 'nome': 'tenis', 'valor': 100, 'quantidade': 3, 'descrição': 'Azul'},
                              {'codigo': 6, 'nome': 'casa', 'valor': 150, 'quantidade': 5, 'descrição': ''}],
                 'saldo': 1000,
                 'historico': []}]
